import { degToRad } from "@/lib/sim/math";
import type {
  EnvironmentProfile,
  MissionProfile,
  ScenarioPreset,
  SensorPolicy,
} from "@/lib/sim/types";

const passiveSensorPolicy: SensorPolicy = {
  passiveOnly: true,
  allowVisible: true,
  allowThermal: true,
  terminalHandoffRange: 7.2,
  terminalCommitRange: 3.9,
  reacquireRange: 10.8,
  activeAssistanceEnabled: false,
};

export const environmentProfiles: Record<string, EnvironmentProfile> = {
  "day-land-normal": {
    id: "day-land-normal",
    name: "Day / Land",
    timeOfDay: "day",
    surfaceType: "land",
    emissionMode: "normal",
    description: "Bright daytime airspace over land with high visible contrast.",
    visibleSNR: 1,
    thermalContrast: 0.72,
    horizonAmbiguity: 0.08,
    glint: 0.05,
    clearColor: "#87a3c7",
    fogColor: "#dce5ea",
    fogDensity: 0.0004,
    ambientIntensity: 0.04,
    keyLightIntensity: 2.05,
    fillLightIntensity: 0.16,
    keyLightColor: "#f7fbff",
    fillLightColor: "#bfd3e0",
    keyLightAzimuth: 0.68,
    keyLightElevation: 0.94,
    backgroundPreset: "land",
  },
  "day-water-normal": {
    id: "day-water-normal",
    name: "Day / Water",
    timeOfDay: "day",
    surfaceType: "water",
    emissionMode: "normal",
    description: "High-glint daytime tanker track over water.",
    visibleSNR: 0.85,
    thermalContrast: 0.66,
    horizonAmbiguity: 0.22,
    glint: 0.34,
    clearColor: "#6f89b8",
    fogColor: "#c7d6df",
    fogDensity: 0.0005,
    ambientIntensity: 0.035,
    keyLightIntensity: 1.9,
    fillLightIntensity: 0.14,
    keyLightColor: "#f5fbff",
    fillLightColor: "#b0d0e0",
    keyLightAzimuth: 0.62,
    keyLightElevation: 0.86,
    backgroundPreset: "water",
  },
  "night-land-passive": {
    id: "night-land-passive",
    name: "Night / Land",
    timeOfDay: "night",
    surfaceType: "land",
    emissionMode: "normal",
    description: "Moonlit overland track using passive visible/thermal handoff.",
    visibleSNR: 0.42,
    thermalContrast: 0.94,
    horizonAmbiguity: 0.18,
    glint: 0.04,
    clearColor: "#040913",
    fogColor: "#0d1520",
    fogDensity: 0.00078,
    ambientIntensity: 0.012,
    keyLightIntensity: 0.42,
    fillLightIntensity: 0.06,
    keyLightColor: "#b6c9ff",
    fillLightColor: "#456079",
    keyLightAzimuth: 1.1,
    keyLightElevation: 0.26,
    backgroundPreset: "land",
  },
  "night-water-passive": {
    id: "night-water-passive",
    name: "Night / Water",
    timeOfDay: "night",
    surfaceType: "water",
    emissionMode: "normal",
    description: "Low-light open-water track with strong thermal preference.",
    visibleSNR: 0.28,
    thermalContrast: 0.88,
    horizonAmbiguity: 0.32,
    glint: 0.14,
    clearColor: "#02060e",
    fogColor: "#09111a",
    fogDensity: 0.0009,
    ambientIntensity: 0.008,
    keyLightIntensity: 0.28,
    fillLightIntensity: 0.045,
    keyLightColor: "#9db4ef",
    fillLightColor: "#33506d",
    keyLightAzimuth: 1.24,
    keyLightElevation: 0.18,
    backgroundPreset: "water",
  },
  "day-land-emcon": {
    id: "day-land-emcon",
    name: "Day / Land / EMCON",
    timeOfDay: "day",
    surfaceType: "land",
    emissionMode: "EMCON",
    description: "Strict emissions control with passive-only sensing over land.",
    visibleSNR: 0.95,
    thermalContrast: 0.7,
    horizonAmbiguity: 0.1,
    glint: 0.05,
    clearColor: "#7f9cbf",
    fogColor: "#d6e0e5",
    fogDensity: 0.00042,
    ambientIntensity: 0.03,
    keyLightIntensity: 1.85,
    fillLightIntensity: 0.11,
    keyLightColor: "#eef7ff",
    fillLightColor: "#9eb7c7",
    keyLightAzimuth: 0.74,
    keyLightElevation: 0.9,
    backgroundPreset: "land",
  },
  "night-water-emcon": {
    id: "night-water-emcon",
    name: "Night / Water / EMCON",
    timeOfDay: "night",
    surfaceType: "water",
    emissionMode: "EMCON",
    description: "Hardest operating envelope: passive-only night refueling over water in EMCON.",
    visibleSNR: 0.2,
    thermalContrast: 0.82,
    horizonAmbiguity: 0.36,
    glint: 0.1,
    clearColor: "#01040b",
    fogColor: "#070d14",
    fogDensity: 0.001,
    ambientIntensity: 0.006,
    keyLightIntensity: 0.22,
    fillLightIntensity: 0.038,
    keyLightColor: "#90a8e6",
    fillLightColor: "#2c4760",
    keyLightAzimuth: 1.28,
    keyLightElevation: 0.14,
    backgroundPreset: "water",
  },
};

export const missionProfiles: Record<string, MissionProfile> = {
  "passive-normal": {
    id: "passive-normal",
    name: "Passive Multispectral",
    description: "Passive visible/thermal sensing with no active aids.",
    emissionMode: "normal",
    passiveOnly: true,
    supportsNight: true,
    supportsWater: true,
    supportsEmcon: true,
  },
  "passive-emcon": {
    id: "passive-emcon",
    name: "Passive Multispectral / EMCON",
    description: "Passive-only architecture with active emissions hard-disabled.",
    emissionMode: "EMCON",
    passiveOnly: true,
    supportsNight: true,
    supportsWater: true,
    supportsEmcon: true,
  },
};

export const scenarioPresets: ScenarioPreset[] = [
  {
    id: "steady-approach",
    name: "Steady Approach",
    description: "Baseline day-land mission with a clean passive intercept window.",
    receiverBasePose: {
      position: { x: 0.35, y: -2.82, z: 14.7 },
      rotation: { x: 0.01, y: -0.022, z: 0.004 },
    },
    motion: {
      translationAmplitude: { x: 0.7, y: 0.4, z: 0.55 },
      translationFrequency: { x: 0.48, y: 0.74, z: 0.42 },
      translationNoise: { x: 0.08, y: 0.06, z: 0.07 },
      rotationAmplitude: { x: degToRad(1.2), y: degToRad(1.5), z: degToRad(1.0) },
      rotationFrequency: { x: 0.32, y: 0.28, z: 0.38 },
    },
    environment: environmentProfiles["day-land-normal"],
    mission: missionProfiles["passive-normal"],
    sensorPolicy: passiveSensorPolicy,
    perception: {
      positionNoise: 0.07,
      pixelNoise: 0.01,
      dropoutProbability: 0.03,
      confidenceFloor: 0.5,
    },
    controller: {
      alignTolerance: 0.34,
      insertTolerance: 0.22,
      mateTolerance: 0.12,
      standbyExtend: 8.1,
      searchAmplitude: { x: 0.38, y: 0.2, z: 0.18 },
      closureGain: 0.7,
      maxBodyStep: 0.08,
    },
    safety: {
      keepOutRadius: 1.28,
      nearTargetDistance: 1.2,
      maxClosureRate: 0.8,
      sensorDisagreementAbort: 0.7,
      sensorDisagreementHold: 0.42,
      receiverMotionSpike: 1.32,
    },
  },
  {
    id: "crosswind-chase",
    name: "Crosswind Chase",
    description: "Day-water mission with more lateral drift and horizon ambiguity.",
    receiverBasePose: {
      position: { x: 0.95, y: -2.72, z: 15.1 },
      rotation: { x: degToRad(-0.4), y: degToRad(-2.8), z: degToRad(0.25) },
    },
    motion: {
      translationAmplitude: { x: 1.25, y: 0.62, z: 0.82 },
      translationFrequency: { x: 0.78, y: 0.88, z: 0.58 },
      translationNoise: { x: 0.16, y: 0.1, z: 0.1 },
      rotationAmplitude: { x: degToRad(2.0), y: degToRad(2.4), z: degToRad(1.6) },
      rotationFrequency: { x: 0.46, y: 0.4, z: 0.54 },
    },
    environment: environmentProfiles["day-water-normal"],
    mission: missionProfiles["passive-normal"],
    sensorPolicy: passiveSensorPolicy,
    perception: {
      positionNoise: 0.1,
      pixelNoise: 0.018,
      dropoutProbability: 0.06,
      confidenceFloor: 0.38,
    },
    controller: {
      alignTolerance: 0.4,
      insertTolerance: 0.26,
      mateTolerance: 0.14,
      standbyExtend: 8.4,
      searchAmplitude: { x: 0.44, y: 0.24, z: 0.2 },
      closureGain: 0.72,
      maxBodyStep: 0.082,
    },
    safety: {
      keepOutRadius: 1.34,
      nearTargetDistance: 1.28,
      maxClosureRate: 0.82,
      sensorDisagreementAbort: 0.76,
      sensorDisagreementHold: 0.46,
      receiverMotionSpike: 1.48,
    },
  },
  {
    id: "sensor-degraded",
    name: "Night Land Passive",
    description: "Nighttime passive mission over land with thermal-primary close-in sensing.",
    receiverBasePose: {
      position: { x: -0.45, y: -2.9, z: 14.85 },
      rotation: { x: degToRad(0.5), y: degToRad(1.6), z: degToRad(-0.2) },
    },
    motion: {
      translationAmplitude: { x: 0.92, y: 0.54, z: 0.74 },
      translationFrequency: { x: 0.58, y: 0.82, z: 0.46 },
      translationNoise: { x: 0.14, y: 0.11, z: 0.1 },
      rotationAmplitude: { x: degToRad(1.9), y: degToRad(1.9), z: degToRad(1.4) },
      rotationFrequency: { x: 0.4, y: 0.34, z: 0.46 },
    },
    environment: environmentProfiles["night-land-passive"],
    mission: missionProfiles["passive-normal"],
    sensorPolicy: passiveSensorPolicy,
    perception: {
      positionNoise: 0.11,
      pixelNoise: 0.02,
      dropoutProbability: 0.08,
      confidenceFloor: 0.32,
    },
    controller: {
      alignTolerance: 0.42,
      insertTolerance: 0.28,
      mateTolerance: 0.15,
      standbyExtend: 8.35,
      searchAmplitude: { x: 0.5, y: 0.28, z: 0.24 },
      closureGain: 0.66,
      maxBodyStep: 0.078,
    },
    safety: {
      keepOutRadius: 1.36,
      nearTargetDistance: 1.34,
      maxClosureRate: 0.78,
      sensorDisagreementAbort: 0.7,
      sensorDisagreementHold: 0.44,
      receiverMotionSpike: 1.38,
    },
  },
  {
    id: "night-water-passive",
    name: "Night Water Passive",
    description: "Open-water nighttime passive tanker track with thermal-dominant sensing.",
    receiverBasePose: {
      position: { x: 0.68, y: -2.96, z: 15.25 },
      rotation: { x: degToRad(-0.3), y: degToRad(-1.9), z: degToRad(0.18) },
    },
    motion: {
      translationAmplitude: { x: 1.08, y: 0.6, z: 0.9 },
      translationFrequency: { x: 0.66, y: 0.9, z: 0.54 },
      translationNoise: { x: 0.18, y: 0.12, z: 0.12 },
      rotationAmplitude: { x: degToRad(2.15), y: degToRad(2.25), z: degToRad(1.55) },
      rotationFrequency: { x: 0.46, y: 0.38, z: 0.5 },
    },
    environment: environmentProfiles["night-water-passive"],
    mission: missionProfiles["passive-normal"],
    sensorPolicy: passiveSensorPolicy,
    perception: {
      positionNoise: 0.12,
      pixelNoise: 0.022,
      dropoutProbability: 0.1,
      confidenceFloor: 0.28,
    },
    controller: {
      alignTolerance: 0.46,
      insertTolerance: 0.3,
      mateTolerance: 0.16,
      standbyExtend: 8.45,
      searchAmplitude: { x: 0.54, y: 0.3, z: 0.26 },
      closureGain: 0.64,
      maxBodyStep: 0.076,
    },
    safety: {
      keepOutRadius: 1.24,
      nearTargetDistance: 1.38,
      maxClosureRate: 0.76,
      sensorDisagreementAbort: 0.72,
      sensorDisagreementHold: 0.46,
      receiverMotionSpike: 1.48,
    },
  },
  {
    id: "day-land-emcon",
    name: "Day Land EMCON",
    description: "Strict EMCON profile: passive-only visible/thermal over land.",
    receiverBasePose: {
      position: { x: 0.25, y: -2.8, z: 14.95 },
      rotation: { x: degToRad(0.15), y: degToRad(-1.2), z: degToRad(0.08) },
    },
    motion: {
      translationAmplitude: { x: 0.82, y: 0.46, z: 0.68 },
      translationFrequency: { x: 0.52, y: 0.74, z: 0.44 },
      translationNoise: { x: 0.1, y: 0.08, z: 0.08 },
      rotationAmplitude: { x: degToRad(1.4), y: degToRad(1.7), z: degToRad(1.05) },
      rotationFrequency: { x: 0.34, y: 0.28, z: 0.42 },
    },
    environment: environmentProfiles["day-land-emcon"],
    mission: missionProfiles["passive-emcon"],
    sensorPolicy: passiveSensorPolicy,
    perception: {
      positionNoise: 0.08,
      pixelNoise: 0.012,
      dropoutProbability: 0.04,
      confidenceFloor: 0.44,
    },
    controller: {
      alignTolerance: 0.36,
      insertTolerance: 0.24,
      mateTolerance: 0.13,
      standbyExtend: 8.2,
      searchAmplitude: { x: 0.36, y: 0.22, z: 0.18 },
      closureGain: 0.68,
      maxBodyStep: 0.08,
    },
    safety: {
      keepOutRadius: 1.32,
      nearTargetDistance: 1.24,
      maxClosureRate: 0.78,
      sensorDisagreementAbort: 0.68,
      sensorDisagreementHold: 0.4,
      receiverMotionSpike: 1.34,
    },
  },
  {
    id: "night-water-emcon",
    name: "Night Water EMCON",
    description: "Strict EMCON at night over water with passive thermal handoff only.",
    receiverBasePose: {
      position: { x: 0.88, y: -3.05, z: 15.45 },
      rotation: { x: degToRad(-0.4), y: degToRad(-2.2), z: degToRad(0.22) },
    },
    motion: {
      translationAmplitude: { x: 1.18, y: 0.66, z: 0.96 },
      translationFrequency: { x: 0.72, y: 0.96, z: 0.6 },
      translationNoise: { x: 0.2, y: 0.14, z: 0.14 },
      rotationAmplitude: { x: degToRad(2.4), y: degToRad(2.45), z: degToRad(1.75) },
      rotationFrequency: { x: 0.52, y: 0.44, z: 0.58 },
    },
    environment: environmentProfiles["night-water-emcon"],
    mission: missionProfiles["passive-emcon"],
    sensorPolicy: passiveSensorPolicy,
    perception: {
      positionNoise: 0.14,
      pixelNoise: 0.026,
      dropoutProbability: 0.12,
      confidenceFloor: 0.24,
    },
    controller: {
      alignTolerance: 0.5,
      insertTolerance: 0.32,
      mateTolerance: 0.17,
      standbyExtend: 8.55,
      searchAmplitude: { x: 0.56, y: 0.32, z: 0.28 },
      closureGain: 0.62,
      maxBodyStep: 0.074,
    },
    safety: {
      keepOutRadius: 1.42,
      nearTargetDistance: 1.42,
      maxClosureRate: 0.72,
      sensorDisagreementAbort: 0.74,
      sensorDisagreementHold: 0.48,
      receiverMotionSpike: 1.56,
    },
  },
];

export function getScenarioById(id: string) {
  return scenarioPresets.find((scenario) => scenario.id === id) ?? scenarioPresets[0];
}
